version: '3.1'

services:
  # Service MongoDB
  mongodb:
    image: mongo:latest
    container_name: ystream-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: YStream
    volumes:
      - mongodb-data:/data/db

  # Service RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: YStream
      RABBITMQ_DEFAULT_PASS: Ystream1234
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongodb-data:
  rabbitmq-data:
